const colors = {
  light: {
    text: "#1A3A4A",
    tint: "#2C6B7F",
    background: "#F0F6F8",
    foreground: "#1A3A4A",
    card: "#FFFFFF",
    cardForeground: "#1A3A4A",
    primary: "#2C6B7F",
    primaryForeground: "#FFFFFF",
    secondary: "#A7D7E8",
    secondaryForeground: "#1A3A4A",
    muted: "#E8F4F8",
    mutedForeground: "#5A8A9F",
    accent: "#D4A24E",
    accentForeground: "#FFFFFF",
    destructive: "#E74C3C",
    destructiveForeground: "#FFFFFF",
    border: "#C5DFE8",
    input: "#E8F4F8",
    success: "#27AE60",
    warning: "#F39C12",
    surface: "#FFFFFF",
    overlay: "rgba(26, 58, 74, 0.5)",
  },
  dark: {
    text: "#E0F0F5",
    tint: "#4A9DB5",
    background: "#0D1F28",
    foreground: "#E0F0F5",
    card: "#152936",
    cardForeground: "#E0F0F5",
    primary: "#2C6B7F",
    primaryForeground: "#FFFFFF",
    secondary: "#1A3A4A",
    secondaryForeground: "#A7D7E8",
    muted: "#1A3A4A",
    mutedForeground: "#5A8A9F",
    accent: "#D4A24E",
    accentForeground: "#FFFFFF",
    destructive: "#E74C3C",
    destructiveForeground: "#FFFFFF",
    border: "#2C5A70",
    input: "#1A3A4A",
    success: "#27AE60",
    warning: "#F39C12",
    surface: "#152936",
    overlay: "rgba(0, 0, 0, 0.7)",
  },
  radius: 12,
};

export default colors;
